### ISSUE TITLE
文件预览文本类型有此文字看不清

### ISSUE THREAD

**Issue by Jousimies** [emacs-eaf/eaf-file-manager#33]
![Screenshot from 2021-08-27 16-34-15](https://user-images.githubusercontent.com/72933939/131122033-e3348f63-db07-4174-88e4-c6fa0f4ab777.png)

**Comment by manateelazycat** [comment]
目前还没有研究清楚Vue.js怎么动态的加载CSS, 目前的CSS代码只对深色主题比较友好。

**Comment by manateelazycat** [comment]
Fixed by newest version.
