### ISSUE TITLE
Dark Mode On or Off based on Emacs Daemon Mode

### ISSUE THREAD

**Issue by nbfields** [emacs-eaf/eaf-file-manager#50]
**Describe the bug**

My .emacs contains the following code:
```
(load-theme 'tango-dark)

; some other settings

(require 'eaf)
(require 'eaf-browser)
(require 'eaf-pdf-viewer)
(require 'eaf-terminal)
(require 'eaf-video-player)
(require 'eaf-file-manager)
(require 'eaf-demo)
(require 'eaf-evil)

; some other settings

(setq eaf-terminal-dark-mode "nil")
(setq eaf-pdf-dark-mode "nil")
(setq eaf-file-manager-dark-mode "nil")

```
The intention of this code is to disable dark mode on PDFs, the terminal, and the file manager. The linked screenshot in the screenshot section shows the appearance of the file manager in a "regular" emacs instance, versus one that is created via "emacs --daemon". As may be seen, the appearence is not the same. The regular emacs instance has a blueish background, which is the default appearance of my terminal and what I would like to see. The daemonized version is all black and it is hard to see the files in the file manager. The colors are likewise in the terminal and PDFs - not shown, but I can provide more screenshots if desired.
 
**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
0: Set up a .emacs file with the above code for eaf
1: Run emacs --daemon, and launch a window in GUI
2: Run emacs (without --daemon) in GUI
3: Open the file manager with M-x eaf-open-in-file-manager in both emacs clients

**Expected behavior**

Expected behavior is that the emacs clients would both look the same. I am actually not sure what the "expected" appearance is as far as the desired behavior from the development perspective. My *preference* is that the file manager etc inherit the same color scheme as my regular work, ie tango-dark, but I do not know which, if any, settings are intended to look like this.

**Versions (please complete the following info):**
 - Distro and DE/WM:
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.11.0-38-generic
      Architecture: x86-64

 - Versions of Dependencies: Uncertain how to find/check 
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-06-04

**Screenshots**
[Daemon vs standard](https://imgur.com/a/vMZnwxc)

**Additional context**
As noted, I am actually not entirely certain which of these is "expected" behavior, just that them being different is probably not intended!

**Comment by manateelazycat** [comment]
Switch emacs-application-framework directory, use command 

```
git pull ; ./install-eaf.py
```

upgrade EAF to newest version.

I believe newest version fix this issue, because emacs-daemon can't get theme foreground/background correctly.
