### ISSUE TITLE
Unable to view directories with broken simlinks

### ISSUE THREAD

**Issue by nbfields** [emacs-eaf/eaf-file-manager#51]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
Traceback (most recent call last):
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 936, in run
    file_infos = self.get_files_callback(self.file)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 243, in get_file_infos
    file_infos.append(self.get_file_info(str(p.absolute())))
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 234, in get_file_info
    "mtime": os.path.getmtime(file_path)
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/nbfields/test_directory/also_no_real'
Traceback (most recent call last):
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 936, in run
    file_infos = self.get_files_callback(self.file)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 243, in get_file_infos
    file_infos.append(self.get_file_info(str(p.absolute())))
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 234, in get_file_info
    "mtime": os.path.getmtime(file_path)
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/nbfields/test_directory/also_no_real'
```

**Describe the bug**

When using the EAF file manager, directories that contain broken simlinks cannot be displayed. They simply show a blank screen, and attempting to show or hide hidden files results in an error: [EAF/file-manager] Cannot execute function: toggle_hidden_file (f81b-41d0-c654-9a74-f27c-39d4-8a9f)

**To Reproduce**

1: Create a directory called test_directory
2: Create a file called test_file in that directory
3: Create a simlink that does not exist, ie `ln -s not_real also_not_real`
4: Open the EAF file manager and attempt to open that directory
5: Switch to the EAF terminal and remove the broken simlink (or do something else to remove it)
6: Return to the file manager (possibly killing the buffer and reopening it) to see the directory is now usable

**Expected behavior**
The EAF file manager would display all files as expected, perhaps highlighting the broken simlink in red or some such to indicate that it is not usable.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 20.04.3 LTS - Window Manager AwesomeWM
 - Versions of Dependencies: Unknown
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-11-04

**Additional context**

There is the obvious solution of simply not having any broken simlinks, but the program Steam creates one in the home directory every time it opens! This is for some backwards compatibility with an older version of the Steam Development Kit or something to that effect, where the link must exist but is unused, so it is created and then broken intentionally. I can delete it each time, but I am pretty sure this is not desired behavior regardless.

**Comment by manateelazycat** [comment]
Has fixed this issue, thanks for report.
