### ISSUE TITLE
文件类型的图标预览优化（Excel PPT org）

### ISSUE THREAD

**Issue by lijigang** [emacs-eaf/eaf-file-manager#56]
**现状**

![image](https://user-images.githubusercontent.com/4835998/191944402-6d8945f2-f524-475f-9a5c-3e46410bb89b.png)
![image](https://user-images.githubusercontent.com/4835998/191944451-e9dcad7f-4f71-46e6-b939-d626a634e4e5.png)
![image](https://user-images.githubusercontent.com/4835998/191944605-73a26380-5149-4eee-a73d-74833e80530c.png)

eaf-file-manager 列表中的文件类型预览图标，Excel、PPT、Orgmode 文件如上图。

**优化**

是否可以把这些文件图标预览做个升级替换？

**Comment by manateelazycat** [comment]
已经修复。
