### ISSUE TITLE
File manager gets stuck on opening directory

### ISSUE THREAD

**Issue by Trent-Fellbootman** [emacs-eaf/eaf-file-manager#78]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.

- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
[JavaScript console]: Uncaught ReferenceError: updateGitLog is not defined
[JavaScript console]: Uncaught TypeError: Cannot read properties of undefined (reading 'install')
[JavaScript console]: Uncaught ReferenceError: init is not defined
[JavaScript console]: Uncaught ReferenceError: changePath is not defined
[JavaScript console]: Uncaught ReferenceError: updateGitLog is not defined
[JavaScript console]: Uncaught ReferenceError: setPreview is not defined
[JavaScript console]: Uncaught ReferenceError: setPreviewOption is not defined
[JavaScript console]: Uncaught ReferenceError: setPreviewOption is not defined
```

**Describe the bug**
EAF file manager gets stuck on opening any directory.

**To Reproduce**
Open up emacs and `<M-x>eaf-open-file-manager<RET>`.

**Expected behavior**
EAF file manager opens correctly.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 22.04
 - Versions of Dependencies:
 - M-x emacs-version: 27.1

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
how did you install EAF

**Comment by Trent-Fellbootman** [comment]
I just did what the README said, namely:

```bash
git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/

cd emacs-application-framework
chmod +x ./install-eaf.py
./install-eaf.py
```

Then I saw some pip and npm installs and was reported that 25/26 apps I selected was installed properly.

By the way, I'm using spacemacs. Is that a possible cause for the problem?

**Comment by robertzhouxh** [comment]
+1

**Comment by manateelazycat** [comment]
please use emacs -Q for compare test.

**Comment by Trent-Fellbootman** [comment]
> please use emacs -Q for compare test.

I used `emacs -Q` then `load-file .spacemacs` and `eaf-open-file-manager`. It still gets stuck but this time there is no error nor output from the `eaf` buffer.

Here's a screenshot of the buffer list and the EAF buffer:

![image](https://github.com/emacs-eaf/eaf-file-manager/assets/78004741/c093981e-1f11-42d1-bd7a-ebd63c57bef1)

**Comment by Trent-Fellbootman** [comment]
> 请只用 emacs -Q ， 然后只加载 EAF 配置进行对比测试， 不要加载其他插件。
> 
> 我每天都在用文件管理器， 目前没有重现你说的问题。

好吧，大家都是中国人\lol

我把之前的emacs.d直接屏蔽掉了（`mv .emacs.d .emacs.d.bak`），然后重新安装EAF并`emacs -Q`打开emacs后使用`eval-expression`加载了`eaf`和`eaf-file-manager`，还是出现一样的问题：

![image](https://github.com/emacs-eaf/eaf-file-manager/assets/78004741/709d8797-5b44-439e-8466-fefa624f111f)

**Comment by Trent-Fellbootman** [comment]
感觉这个问题挺魔性的，因为它说找不到的这些方法在file-manager的Vue源码里面都有定义

**Comment by Trent-Fellbootman** [comment]
另外之前这个图应该有误，我当时误操作了开了个叫`eaf`的新buffer而不是`*eaf*`，看`*eaf*`的长度应该还是有报错的\lol

> > please use emacs -Q for compare test.
> 
> I used `emacs -Q` then `load-file .spacemacs` and `eaf-open-file-manager`. It still gets stuck but this time there is no error nor output from the `eaf` buffer.
> 
> Here's a screenshot of the buffer list and the EAF buffer:
> 
> ![image](https://private-user-images.githubusercontent.com/78004741/287284523-c093981e-1f11-42d1-bd7a-ebd63c57bef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0OTM1ODEsIm5iZiI6MTcwMTQ5MzI4MSwicGF0aCI6Ii83ODAwNDc0MS8yODcyODQ1MjMtYzA5Mzk4MWUtMWYxMS00MmQxLWJkN2EtZWJkNjNjNTdiZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDA1MDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNzQ4YzE3NzI5ZTRjZWQ5ZmJmNTkwMDVjYjgzMmVlMTk5NzVkMWRkMzRiOTNkMDg3NmRkNDA4ZDhiNTQwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8BcE5fediowmIH7dhEX7y-qYmv45XQae6yOGLxWr90)

**Comment by manateelazycat** [comment]
切换到 emacs-application-framework/app/file-manager 目录
执行命令 rm -rf ./node_modules 删除旧的npm包
git pull --rebase 更新到最新版
npm install ; npm run build 重新构建file-manager的JS部分
重新启动 EAF 就可以了

原因是因为Github机器人提示升级 axios 这个包后， 我在外出差没有重新构建来测试， 引入的新问题。

已经修复了， 感谢提醒。
