### ISSUE TITLE
How can I customize the font used in eaf-file-manager?

### ISSUE THREAD

**Issue by oscarvarto** [emacs-eaf/eaf-file-manager#79]
**Is your feature request related to a problem? Please describe.**
I'd like to keep using my main font (PragmataPro) in eaf-file-manager, but I don't know how to customize it.

**Describe the solution you'd like**
Is there a variable to choose the font, or should I hardcode the font family somewhere in the code?

**Describe alternatives you've considered**
With `eaf-pyqterminal`, I can use something like (Doom Emacs user here):
```
(after! eaf-pyqterminal
  (setq eaf-pyqterminal-font-family "PragmataPro Mono Liga")
  (setq eaf-pyqterminal-font-size 14)
  )
```

**Additional context**
$ uname -a
Linux optimus 6.6.7-2-cachyos #1 SMP PREEMPT_DYNAMIC Sat, 16 Dec 2023 09:07:35 +0000 x86_64 GNU/Linux

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/blob/6115133f822afb44268578f4971919edd2cc63eb/site-lisp/config/init-eaf.el#L140
